package routes_test

import (
	"fmt"
	"testing"

	"github.com/browningluke/terraform-provider-opnsense/internal/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// Gateway names auto-generated by OPNsense on a clean single-NIC (wan) install.
const (
	testRouteGateway   = "WAN_DHCP"
	testRouteGatewayV6 = "WAN_DHCP6"
)

func TestAccRouteResource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccPreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccRouteResourceConfig(testRouteGateway, "192.0.2.0/24"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("opnsense_route.test", "enabled", "true"),
					resource.TestCheckResourceAttr("opnsense_route.test", "gateway", testRouteGateway),
					resource.TestCheckResourceAttr("opnsense_route.test", "network", "192.0.2.0/24"),
					resource.TestCheckResourceAttrSet("opnsense_route.test", "id"),
				),
			},
			{
				ResourceName:      "opnsense_route.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				Config: testAccRouteResourceConfig(testRouteGateway, "192.0.2.128/25"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("opnsense_route.test", "network", "192.0.2.128/25"),
				),
			},
		},
	})
}

func TestAccRouteResource_Disabled(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccPreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccRouteResourceConfigDisabled(testRouteGateway, "192.0.2.0/24"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("opnsense_route.test", "enabled", "false"),
					resource.TestCheckResourceAttrSet("opnsense_route.test", "id"),
				),
			},
			{
				ResourceName:      "opnsense_route.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccRouteResource_WithDescription(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccPreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccRouteResourceConfigWithDescription(testRouteGateway, "192.0.2.0/24", "Test static route"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("opnsense_route.test", "description", "Test static route"),
					resource.TestCheckResourceAttrSet("opnsense_route.test", "id"),
				),
			},
			{
				ResourceName:      "opnsense_route.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccRouteResource_IPv6(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccPreCheck(t) },
		ProtoV6ProviderFactories: acctest.ProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccRouteResourceConfig(testRouteGatewayV6, "2001:db8::/32"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("opnsense_route.test", "network", "2001:db8::/32"),
					resource.TestCheckResourceAttrSet("opnsense_route.test", "id"),
				),
			},
			{
				ResourceName:      "opnsense_route.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccRouteResourceConfig(gateway, network string) string {
	return fmt.Sprintf(`
resource "opnsense_route" "test" {
  gateway = %[1]q
  network = %[2]q
}
`, gateway, network)
}

func testAccRouteResourceConfigDisabled(gateway, network string) string {
	return fmt.Sprintf(`
resource "opnsense_route" "test" {
  enabled = false
  gateway = %[1]q
  network = %[2]q
}
`, gateway, network)
}

func testAccRouteResourceConfigWithDescription(gateway, network, description string) string {
	return fmt.Sprintf(`
resource "opnsense_route" "test" {
  gateway     = %[1]q
  network     = %[2]q
  description = %[3]q
}
`, gateway, network, description)
}
