package trust

import (
	"github.com/browningluke/opnsense-go/pkg/api"
	"github.com/browningluke/opnsense-go/pkg/trust"
	dschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type caResourceModel struct {
	Id                 types.String `tfsdk:"id"`
	RefId              types.String `tfsdk:"ref_id"`
	Description        types.String `tfsdk:"description"`
	Action             types.String `tfsdk:"action"`
	Crt                types.String `tfsdk:"crt"`
	Prv                types.String `tfsdk:"prv"`
	Serial             types.String `tfsdk:"serial"`
	CaRef              types.String `tfsdk:"caref"`
	KeyType            types.String `tfsdk:"key_type"`
	Lifetime           types.String `tfsdk:"lifetime"`
	Digest             types.String `tfsdk:"digest"`
	Country            types.String `tfsdk:"country"`
	State              types.String `tfsdk:"state"`
	City               types.String `tfsdk:"city"`
	Organization       types.String `tfsdk:"organization"`
	OrganizationalUnit types.String `tfsdk:"organizational_unit"`
	Email              types.String `tfsdk:"email"`
	CommonName         types.String `tfsdk:"common_name"`
	OcspUri            types.String `tfsdk:"ocsp_uri"`
	CrtPayload         types.String `tfsdk:"crt_payload"`
	PrvPayload         types.String `tfsdk:"prv_payload"`
	Name               types.String `tfsdk:"name"`
	ValidFrom          types.String `tfsdk:"valid_from"`
	ValidTo            types.String `tfsdk:"valid_to"`
}

func caResourceSchema() schema.Schema {
	return schema.Schema{
		MarkdownDescription: "Manages a Certificate Authority in the OPNsense Trust store.",

		Version: 1,

		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UUID of the Certificate Authority.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"ref_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Short hex reference ID used by other OPNsense subsystems (e.g. OpenVPN, IPsec) to reference this CA.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Optional description for this CA.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"action": schema.StringAttribute{
				MarkdownDescription: "Creation action: `internal` (generate a new CA), `existing` (import an existing CA), or `ocsp` (create an OCSP signing certificate). Defaults to `internal`.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("internal"),
			},
			"crt": schema.StringAttribute{
				MarkdownDescription: "Base64-encoded PEM certificate body. Required when `action` is `existing`. Computed (generated by OPNsense) when `action` is `internal`.",
				Optional:            true,
				Computed:            true,
				Sensitive:           false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"prv": schema.StringAttribute{
				MarkdownDescription: "Base64-encoded PEM private key. Computed when `action` is `internal`; optionally provided when `action` is `existing`.",
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"serial": schema.StringAttribute{
				MarkdownDescription: "Next serial number for certificates issued by this CA.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"caref": schema.StringAttribute{
				MarkdownDescription: "Reference ID (`ref_id`) of the parent CA. Used for intermediate CAs or OCSP signers. Leave empty for root CAs.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"key_type": schema.StringAttribute{
				MarkdownDescription: "Key type and size: `512`, `1024`, `2048` (default), `3072`, `4096`, `8192`, `prime256v1`, `secp384r1`, `secp521r1`. Defaults to `2048`.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("2048"),
			},
			"lifetime": schema.StringAttribute{
				MarkdownDescription: "CA validity period in days. Defaults to `3650` (10 years). Note: OPNsense does not return the configured lifetime on subsequent reads; the value stored in Terraform state is preserved.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("3650"),
			},
			"digest": schema.StringAttribute{
				MarkdownDescription: "Digest algorithm: `sha224`, `sha256` (default), `sha384`, `sha512`. Defaults to `sha256`.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString("sha256"),
			},
			"country": schema.StringAttribute{
				MarkdownDescription: "ISO 3166-1 alpha-2 country code (e.g. `US`, `CA`, `DE`).",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"state": schema.StringAttribute{
				MarkdownDescription: "State or province name.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"city": schema.StringAttribute{
				MarkdownDescription: "City or locality name.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"organization": schema.StringAttribute{
				MarkdownDescription: "Organisation name.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"organizational_unit": schema.StringAttribute{
				MarkdownDescription: "Organisational unit name.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"email": schema.StringAttribute{
				MarkdownDescription: "Email address for the CA subject.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"common_name": schema.StringAttribute{
				MarkdownDescription: "Common name (CN) for the CA certificate.",
				Required:            true,
			},
			"ocsp_uri": schema.StringAttribute{
				MarkdownDescription: "OCSP responder URI embedded in issued certificates.",
				Optional:            true,
				Computed:            true,
				Default:             stringdefault.StaticString(""),
			},
			"crt_payload": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Decoded PEM certificate body (read-only).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"prv_payload": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				MarkdownDescription: "Decoded PEM private key (read-only, sensitive).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Distinguished name string of the CA (read-only).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"valid_from": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unix timestamp of certificate start date (read-only).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"valid_to": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unix timestamp of certificate expiry date (read-only).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func caDataSourceSchema() dschema.Schema {
	return dschema.Schema{
		MarkdownDescription: "Retrieves a Trust Certificate Authority by UUID.",

		Attributes: map[string]dschema.Attribute{
			"id": dschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "UUID of the Certificate Authority.",
			},
			"ref_id": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Short hex reference ID used by other OPNsense subsystems to reference this CA.",
			},
			"description": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Description of the CA.",
			},
			"action": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Creation action used for this CA.",
			},
			"crt": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Base64-encoded PEM certificate body.",
			},
			"serial": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Next serial number.",
			},
			"caref": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Reference ID of the parent CA.",
			},
			"key_type": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Key type and size.",
			},
			"lifetime": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Certificate validity period in days (template value).",
			},
			"digest": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Digest algorithm.",
			},
			"country": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "ISO 3166-1 alpha-2 country code.",
			},
			"state": dschema.StringAttribute{
				Computed: true,
			},
			"city": dschema.StringAttribute{
				Computed: true,
			},
			"organization": dschema.StringAttribute{
				Computed: true,
			},
			"organizational_unit": dschema.StringAttribute{
				Computed: true,
			},
			"email": dschema.StringAttribute{
				Computed: true,
			},
			"common_name": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Common name (CN) of the CA certificate.",
			},
			"ocsp_uri": dschema.StringAttribute{
				Computed: true,
			},
			"crt_payload": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Decoded PEM certificate body.",
			},
			"prv_payload": dschema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				MarkdownDescription: "Decoded PEM private key (sensitive).",
			},
			"name": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Distinguished name string of the CA.",
			},
			"valid_from": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unix timestamp of certificate start date.",
			},
			"valid_to": dschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unix timestamp of certificate expiry date.",
			},
		},
	}
}

func convertCaSchemaToStruct(d *caResourceModel) (*trust.Ca, error) {
	return &trust.Ca{
		Description:        d.Description.ValueString(),
		Action:             api.SelectedMap(d.Action.ValueString()),
		Crt:                d.Crt.ValueString(),
		Prv:                d.Prv.ValueString(),
		CaRef:              api.SelectedMap(d.CaRef.ValueString()),
		KeyType:            api.SelectedMap(d.KeyType.ValueString()),
		Lifetime:           d.Lifetime.ValueString(),
		Digest:             api.SelectedMap(d.Digest.ValueString()),
		Country:            api.SelectedMap(d.Country.ValueString()),
		State:              d.State.ValueString(),
		City:               d.City.ValueString(),
		Organization:       d.Organization.ValueString(),
		OrganizationalUnit: d.OrganizationalUnit.ValueString(),
		Email:              d.Email.ValueString(),
		CommonName:         d.CommonName.ValueString(),
		OcspUri:            d.OcspUri.ValueString(),
	}, nil
}

func convertCaStructToSchema(d *trust.Ca) (*caResourceModel, error) {
	model := &caResourceModel{
		Description:        types.StringValue(d.Description),
		Action:             types.StringValue(d.Action.String()),
		Crt:                types.StringValue(d.Crt),
		Prv:                types.StringValue(d.Prv),
		CaRef:              types.StringValue(d.CaRef.String()),
		KeyType:            types.StringValue(d.KeyType.String()),
		Lifetime:           types.StringValue(d.Lifetime),
		Digest:             types.StringValue(d.Digest.String()),
		Country:            types.StringValue(d.Country.String()),
		State:              types.StringValue(d.State),
		City:               types.StringValue(d.City),
		Organization:       types.StringValue(d.Organization),
		OrganizationalUnit: types.StringValue(d.OrganizationalUnit),
		Email:              types.StringValue(d.Email),
		CommonName:         types.StringValue(d.CommonName),
		OcspUri:            types.StringValue(d.OcspUri),
	}
	if d.RefId != "" {
		model.RefId = types.StringValue(d.RefId)
	} else {
		model.RefId = types.StringNull()
	}
	if d.Serial != "" {
		model.Serial = types.StringValue(d.Serial)
	} else {
		model.Serial = types.StringNull()
	}
	if d.CrtPayload != "" {
		model.CrtPayload = types.StringValue(d.CrtPayload)
	} else {
		model.CrtPayload = types.StringNull()
	}
	if d.PrvPayload != "" {
		model.PrvPayload = types.StringValue(d.PrvPayload)
	} else {
		model.PrvPayload = types.StringNull()
	}
	if d.Name != "" {
		model.Name = types.StringValue(d.Name)
	} else {
		model.Name = types.StringNull()
	}
	if d.ValidFrom != "" {
		model.ValidFrom = types.StringValue(d.ValidFrom)
	} else {
		model.ValidFrom = types.StringNull()
	}
	if d.ValidTo != "" {
		model.ValidTo = types.StringValue(d.ValidTo)
	} else {
		model.ValidTo = types.StringNull()
	}
	return model, nil
}
