name: Go Generate Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-go-generate:
    name: Ensure go generate is up to date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - name: Run go generate
        run: go generate ./...

      - name: Check for uncommitted changes
        run: |
          if ! git diff --exit-code; then
            echo "⚠️ 'go generate' resulted in changes. Please run 'go generate ./...' and commit the results."
            git diff
            exit 1
          fi
